### ISSUE TITLE
Potentially reduce network command usage

### ISSUE THREAD

**Issue by ampersand38** [omartynenko/_arma3_re_series#2]
Since `setUnitTrait` effects are sent globally, it would be nice to reduce its usage where posssible.

Each unit could use object-scope variables to store its uniform, surface, and stance, and only run `setUnitTrait` when the camouflageCoef needs to be changed, instead of every cycle.

**Comment by omartynenko** [comment]
Thanks a lot for this! I've implemented the logic you're proposing and published on Steam mentioning your name in Credits for RE.
